# Generated by Django 4.1.5 on 2023-01-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredients_recipe_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipe'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
