# Generated by Django 4.1.5 on 2023-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_options_recipe_name_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='new recipe', max_length=300),
        ),
    ]
