# Generated by Django 4.1.5 on 2023-01-18 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cat',
            field=models.ManyToManyField(help_text='Enter ------', to='recipes.recipecategory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(help_text='Enter a date for Recipe', verbose_name='Recipe Date'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Enter a ------', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/images/default.jpg', help_text='Enter ------', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(help_text='Enter ------'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='new recipe', help_text='Enter a Recipe Name (e.g. Pasta)', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outro',
            field=models.TextField(help_text='Enter ------'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1, help_text='Enter a ------', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(help_text='Enter ------'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timetoprepare',
            field=models.IntegerField(default=1, help_text='Enter ------', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
