# Generated by Django 4.1.5 on 2023-01-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_cat_alter_recipe_date_alter_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='recipe_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe'),
        ),
    ]
