# Generated by Django 4.1.5 on 2023-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredients_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=100),
        ),
    ]
