# Generated by Django 4.1.5 on 2023-01-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_ingredients_salt_remove_ingredients_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('k', 'Kilogram'), ('g', 'Gram'), ('s', 'Spoon'), ('l', 'Liter'), ('p', 'Peymane')], max_length=10),
        ),
    ]
