# Generated by Django 4.1.5 on 2023-01-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/images/default.jpg', help_text='Enter ------', upload_to='images/'),
        ),
    ]
