# Generated by Django 4.1.5 on 2023-01-18 23:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
            ],
        ),
    ]
