# Generated by Django 4.1.5 on 2023-01-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(help_text='Enter ------', on_delete=django.db.models.deletion.CASCADE, to='recipes.gallery'),
        ),
    ]
