# Generated by Django 4.1.5 on 2023-01-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Enter ------', null=True, upload_to='images/'),
        ),
    ]
