# Generated by Django 4.1.5 on 2023-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ManyToManyField(null=True, to='recipes.gallery'),
        ),
    ]
