# Generated by Django 4.1.5 on 2023-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_remove_recipe_image_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Enter ------', null=True, upload_to='images'),
        ),
    ]
