# Generated by Django 4.1.5 on 2023-01-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/recipe_images/default.jpg', help_text='Enter ------', null=True, upload_to='recipes/static/recipe_images/'),
        ),
    ]
