# Generated by Django 4.1.5 on 2023-01-21 00:23

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/recipe_images/default.jpg', force_format='WebP', help_text='Enter ------', keep_meta=True, null=True, quality=80, scale=None, size=[850, 310], upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/recipe_images/default.jpg', force_format='WebP', help_text='Enter ------', keep_meta=True, null=True, quality=80, scale=None, size=[850, 310], upload_to='recipe_images/'),
        ),
    ]
