# Generated by Django 4.1.5 on 2023-01-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_recipecategory_desc_recipecategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'parent categories',
            },
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='recipes.parentcategory'),
        ),
    ]
