# Generated by Django 4.1.5 on 2023-01-21 00:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_parentcategory_recipecategory_parent_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/recipe_images/default.jpg', force_format='WebP', help_text='Enter ------', keep_meta=True, null=True, quality=80, scale=None, size=[850, 310], upload_to='recipe_images/'),
        ),
    ]
