# Generated by Django 4.1.5 on 2023-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_follow_profile_wishlist_review_follow_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/users/default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
