# Generated by Django 4.1.5 on 2023-01-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
