# Generated by Django 4.1.5 on 2023-01-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_rename_user_review_email_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_recipes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='CookedRecipe',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
