# Generated by Django 4.1.5 on 2023-01-27 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0039_recipe_author_recipe_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cat',
            field=models.ManyToManyField(help_text='Select categories for recipe (hold ctrl to select more than one recipe)', to='recipes.recipecategory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.CharField(default='new chef', help_text="recipe's chef name (e.g. Chef John)", max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], help_text='difficulty level (e.g. Easy)', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/recipe_images/default.jpg', force_format='WebP', help_text='choose an image for the recipe', keep_meta=True, null=True, quality=80, scale=None, size=[850, 310], upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(help_text='an introduction for the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='new recipe', help_text='Recipe Name (e.g. Pasta)', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outro',
            field=models.TextField(help_text='add some notes for the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1, help_text='serves (e.g. 4 people)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(help_text='please enter steps for the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timetoprepare',
            field=models.IntegerField(default=1, help_text='time to prepare (e.g. 30 minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
