# Generated by Django 4.1.5 on 2023-01-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_recipe_updated_at_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='recipe_code',
            new_name='recipe',
        ),
    ]
