# Generated by Django 4.1.5 on 2023-01-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_rename_recipe_code_ingredients_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='privacy',
            field=models.BooleanField(default=False, help_text='is this recipe private?'),
        ),
    ]
