# Generated by Django 4.1.5 on 2023-01-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_recipe_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.units'),
        ),
    ]
