# Generated by Django 4.1.5 on 2023-02-01 12:46

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0045_alter_ingredients_recipe_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=django_quill.fields.QuillField(help_text='an introduction for the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=django_quill.fields.QuillField(help_text='please enter steps for the recipe'),
        ),
    ]
