# Generated by Django 4.1.5 on 2023-02-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0046_alter_recipe_intro_alter_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='value',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.CharField(default='common', help_text="recipe's chef name (e.g. Chef John)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(help_text='an introduction for the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Recipe Name (e.g. Pasta)', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outro',
            field=models.TextField(help_text='add some notes for the recipe', null=True),
        ),
    ]
