# Generated by Django 4.1.5 on 2023-02-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0047_alter_ingredients_value_alter_recipe_chef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.CharField(blank=True, default='common', help_text="recipe's chef name (e.g. Chef John)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outro',
            field=models.TextField(blank=True, help_text='add some notes for the recipe', null=True),
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField(auto_created=True)),
                ('step_text', models.TextField()),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'Recipe Steps',
            },
        ),
    ]
