# Generated by Django 4.1.5 on 2023-02-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0048_alter_recipe_chef_alter_recipe_outro_recipesteps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesteps',
            name='step_no',
        ),
    ]
