# Generated by Django 4.1.5 on 2023-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0049_remove_recipesteps_step_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
    ]
