# Generated by Django 4.1.5 on 2023-02-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0051_alter_ingredients_value_alter_recipe_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.BooleanField(default=False, help_text='is this recipe ready to be published?'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cat',
            field=models.ManyToManyField(blank=True, help_text='Select categories for recipe (hold ctrl to select more than one recipe)', to='recipes.recipecats'),
        ),
    ]
