# Generated by Django 4.1.5 on 2023-02-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0052_recipe_status_alter_recipe_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=1, default=1, max_digits=20, null=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.units')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Recipe Instructions',
            },
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.recipeingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='recipes.recipeinstructions'),
        ),
    ]
