# Generated by Django 4.1.5 on 2023-02-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0053_recipeingredients_recipeinstructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'Recipe Ingredient'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recipes.recipeingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(blank=True, to='recipes.recipeinstructions'),
        ),
        migrations.DeleteModel(
            name='RecipeSteps',
        ),
    ]
