# Generated by Django 4.1.5 on 2023-02-08 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0055_recipeingredients_image_recipeinstructions_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(blank=True, default=1, help_text='serves (e.g. 4 people)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
