# Generated by Django 4.1.5 on 2023-02-08 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0056_alter_recipe_serves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], help_text='difficulty level (e.g. Easy)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timetoprepare',
            field=models.IntegerField(blank=True, default=1, help_text='time to prepare (e.g. 30 minutes)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
