# Generated by Django 4.1.5 on 2023-02-12 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0058_alter_recipe_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='default/default-recipe.jpg', force_format='WebP', help_text='choose an image for the recipe', keep_meta=True, null=True, quality=80, scale=None, size=[850, 300], upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipeinstructions',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WebP', keep_meta=True, null=True, quality=80, scale=None, size=[850, 310], upload_to='instructions_images/'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
