# Generated by Django 4.1.5 on 2023-02-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0059_alter_recipe_image_alter_recipeinstructions_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(blank=True, default=1, help_text='difficulty level (e.g. Easy)', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(blank=True, default=1, help_text='serves (e.g. 4 people)', null=True),
        ),
    ]
