# Generated by Django 4.1.5 on 2023-03-02 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0061_reciperating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRating',
            new_name='RecipeReview',
        ),
    ]
