# Generated by Django 4.1.5 on 2023-03-03 00:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0063_alter_recipereview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereview',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WebP', keep_meta=True, null=True, quality=80, scale=None, size=[1080, 720], upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
